=== XuperX/SAPIENTA/ssplit/article-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="pdfx" type="pdfxType" />
  
  <xsd:complexType name="pdfxType">
    <xsd:sequence>
      <xsd:element name="meta" type="metaType" />
      <xsd:element name="article" type="articleType" />
    </xsd:sequence>
    <xsd:attribute name="xsi" type="xsd:string" />
    <xsd:attribute name="noNamespaceSchemaLocation" type="xsd:string" />
  </xsd:complexType>
  
  <xsd:complexType name="metaType">
    <xsd:sequence>
      <xsd:element name="job" type="xsd:string" />    
      <xsd:element name="base_name" type="xsd:string" />
      <xsd:element name="warning" minOccurs="0" maxOccurs="unbounded" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="articleType">
    <xsd:sequence>
      <xsd:element name="front" type="frontType" />
      <xsd:element name="body" type="bodyType" />
    </xsd:sequence>
    <xsd:attribute name="xsi" type="xsd:string" />
    <xsd:attribute name="noNamespaceSchemaLocation" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="frontType">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="title-group" type="title-groupType" />
      <xsd:element name="contrib-group" type="contrib-groupType" />
      <xsd:element name="outsider" type="mixedType" />
      <xsd:element name="footnote" type="mixedType" />
      <xsd:element name="abstract" type="mixedType" />
      <xsd:element name="region" type="mixedType" />
    </xsd:choice>
    <xsd:attribute name="class" type="xsd:string" />
  </xsd:complexType>
    
  <xsd:complexType name="bodyType">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="section" type="sectionType" />
      <xsd:element name="region" type="mixedType" />
      <xsd:element name="disp-formula" type="dispFormulaType" />
      <xsd:element name="outsider" type="mixedType" />
    </xsd:choice>
    <xsd:attribute name="class" type="xsd:string" />
  </xsd:complexType>
  
  <xsd:complexType name="sectionType">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="h1" type="mixedType" />
      <xsd:element name="h2" type="mixedType" />
      <xsd:element name="h3" type="mixedType" />
      <xsd:element name="h4" type="mixedType" />
      <xsd:element name="h5" type="mixedType" />
      <xsd:element name="region" type="mixedType" />
      <xsd:element name="disp-formula" type="dispFormulaType" />
      <xsd:element name="outsider" type="mixedType" />
      <xsd:element name="ref-list" type="ref-listType" />
      <xsd:element name="section" type="sectionType" />
    </xsd:choice>
    <xsd:attribute name="class" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="contrib-groupType" mixed="true">
	<xsd:sequence maxOccurs="unbounded">
	  <xsd:element name="contrib" type="contribType" />
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:int" />
	<xsd:attribute name="contrib-type" type="xsd:string" />
	<xsd:attribute name="class" type="xsd:string" />
	<xsd:attribute name="page" type="xsd:int" />
	<xsd:attribute name="column" type="xsd:int" />
  </xsd:complexType>
  
  <xsd:complexType name="contribType">
    <xsd:sequence>
      <xsd:element name="name" type="mixedType" />
      <xsd:element name="aff" minOccurs="0" maxOccurs="unbounded" type="mixedType" />
    </xsd:sequence>
    <xsd:attribute name="contrib-type" type="xsd:string" />
  </xsd:complexType>
  
  <xsd:complexType name="title-groupType">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="article-title" type="mixedType" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ext-linkType">
    <xsd:complexContent>
      <xsd:extension base="mixedType">
        <xsd:attribute name="ext-link-type" type="xsd:string" />
        <xsd:attribute name="href" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
    
  <xsd:complexType name="xrefType">
    <xsd:complexContent>
      <xsd:extension base="mixedType">
        <xsd:attribute name="ref-type" type="xsd:string" />
        <xsd:attribute name="rid" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="markerType">
	<xsd:attribute name="type" type="xsd:string"/>
	<xsd:attribute name="number" type="xsd:int"/>
  </xsd:complexType>
  
  <xsd:complexType name="tableContentType">
    <xsd:sequence maxOccurs="unbounded">
	  <xsd:element name="table" type="tableType" />
	</xsd:sequence>
  </xsd:complexType>  
  
  <xsd:complexType name="tableType">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
	  <xsd:element name="thead" type="tableSectionType" />
	  <xsd:element name="tbody" type="tableSectionType" />
	  <xsd:element name="tfoot" type="tableSectionType" />
	</xsd:choice>
	<xsd:attribute name="number" type="xsd:string"/>
	<xsd:attribute name="id" type="xsd:string" />
	<xsd:attribute name="type" type="xsd:string" />
	<xsd:attribute name="class" type="xsd:string" />
	<xsd:attribute name="page" type="xsd:int" />
	<xsd:attribute name="column" type="xsd:int" />
  </xsd:complexType>    
  
  <xsd:complexType name="tableSectionType">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
	  <xsd:element name="tr" type="hdNestedType" />
	</xsd:sequence>
	<xsd:attribute name="number" type="xsd:int"/>
	<xsd:attribute name="id" type="xsd:string" />
	<xsd:attribute name="type" type="xsd:string" />
	<xsd:attribute name="class" type="xsd:string" />
	<xsd:attribute name="page" type="xsd:int" />
	<xsd:attribute name="column" type="xsd:int" />
  </xsd:complexType>    
  
  <xsd:complexType name="hdNestedType">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
	  <xsd:element name="th" type="mixedType" />
	  <xsd:element name="td" type="mixedType" />
	</xsd:choice>
	<xsd:attribute name="class" type="xsd:string" />
  </xsd:complexType>    
  
  <xsd:complexType name="imageType">
	<xsd:attribute name="src" type="xsd:string" />
	<xsd:attribute name="thmb" type="xsd:string" />
    <xsd:attribute name="class" type="xsd:string" />
  </xsd:complexType> 
  
  <xsd:complexType name="dispFormulaType">
    <xsd:sequence maxOccurs="unbounded">
	  <xsd:element name="label" type="mixedType" />
	  <xsd:element name="content" type="mixedType" />
	</xsd:sequence>
	<xsd:attribute name="class" type="xsd:string" /> 
  </xsd:complexType>  
  
  <xsd:complexType name="ref-listType">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="ref" type="refType" />
    </xsd:sequence>
    <xsd:attribute name="class" type="xsd:string" />
  </xsd:complexType>
  
  <xsd:complexType name="refType">
    <xsd:complexContent>
      <xsd:extension base="mixedType">
        <xsd:attribute name="rid" type="xsd:string" />
        <xsd:attribute name="doi" type="xsd:string" />
        <xsd:attribute name="alt_doi" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <xsd:complexType name="mixedType" mixed="true">
	  <xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="region" type="mixedType" />
		<xsd:element name="disp-formula" type="dispFormulaType" />
		<xsd:element name="annotation" type="mixedType" />
		<xsd:element name="aff" type="mixedType" />
		<xsd:element name="email" type="mixedType" />
		<xsd:element name="ext-link" type="ext-linkType" />
		<xsd:element name="xref" type="xrefType" />
		<xsd:element name="marker" type="markerType" />
		<xsd:element name="caption" type="mixedType" />
		<xsd:element name="content" type="tableContentType" />
		<xsd:element name="image" type="imageType" />
      <xsd:element name="s" type="mixedType" />
	  </xsd:choice>
	  <xsd:attribute name="id" type="xsd:string" />
	  <xsd:attribute name="sid" type="xsd:string" />
	  <xsd:attribute name="type" type="xsd:string" />
	  <xsd:attribute name="class" type="xsd:string" />
	  <xsd:attribute name="page" type="xsd:int" />
	  <xsd:attribute name="column" type="xsd:int" />
	  <xsd:attribute name="confidence" type="xsd:string" />
  </xsd:complexType>
   
</xsd:schema>

=== XuperX/SAPIENTA/sapienta/journal.pone.0136492_annotated.xml
<?xml version="1.0" ?><pdfx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://pdfx.cs.man.ac.uk/static/article-schema.xsd">
  <meta>
    <job>7863a997ddc82968dd3b1e7a63b93ef6e953590dbd281df19f404aeba8256e3e</job>
    <base_name>q4s</base_name>
    <doi>10.1371/journal.pone.0136492</doi>
    <warning>Name identification was not possible. </warning>
  </meta>
  <article>
    <front class="DoCO:FrontMatter">
      <region class="DoCO:FigureBox" id="Fx1">
        <image class="DoCO:Figure" src="q4s.page_001.image_01.png" thmb="q4s.page_001.image_01-thumb.png"/>
      </region>
      <region class="unknown" id="2">RESEARCH ARTICLE</region>
      <title-group>
        <article-title class="DoCO:Title" id="3">Infants Time Their Smiles to Make Their Moms Smile</article-title>
      </title-group>
      <region class="unknown" id="5">Paul Ruvolo 1 *, Daniel Messinger 2 , Javier Movellan 3 1 Olin College of Engineering, Department of Engineering, Needham, Massachusetts, United States of America, 2 University of Miami, Department of Psychology, Coral Gables, Florida, United States of America, 3 Institute for Neural Computation, University of California San Diego, La Jolla, California, United States of America * <email id="4">Paul.Ruvolo@olin.edu</email></region>
      <region class="DoCO:FigureBox" id="Fx6">
        <image class="DoCO:Figure" src="q4s.page_001.image_02.png" thmb="q4s.page_001.image_02-thumb.png"/>
        <image class="DoCO:Figure" src="q4s.page_001.image_03.png" thmb="q4s.page_001.image_03-thumb.png"/>
      </region>
      <outsider class="DoCO:TextBox" id="7" type="sidenote">OPEN ACCESS Citation: Ruvolo P, Messinger D, Movellan J (2015) Infants Time Their Smiles to Make Their Moms Smile. PLoS ONE 10(9): e0136492. doi:10.1371/ journal.pone.0136492</outsider>
      <outsider class="DoCO:TextBox" id="8" type="sidenote">Editor: Kim A. Bard, University of Portsmouth, UNITED KINGDOM</outsider>
      <abstract class="DoCO:Abstract" id="9"><s sid="1"><CoreSc1 advantage="None" conceptID="Met1" novelty="None" type="Met"/><text>One of the earliest forms of interaction between mothers and infants is smiling games.</text></s><s sid="2"><CoreSc1 advantage="None" conceptID="Met2" novelty="None" type="Met"/><text> While the temporal dynamics of these games have been extensively studied, they are still not well understood.</text></s><s sid="3"><CoreSc1 advantage="None" conceptID="Met3" novelty="None" type="Met"/><text> Why do mothers and infants time their smiles the way they do?</text></s><s sid="4"><CoreSc1 advantage="None" conceptID="Met4" novelty="None" type="Met"/><text> To answer this question we applied methods from control theory, an approach frequently used in robotics, to analyze and synthesize goal-oriented behavior.</text></s><s sid="5"><CoreSc1 advantage="None" conceptID="Met5" novelty="None" type="Met"/><text> The results of our analysis show that by the time infants reach 4 months of age both mothers and infants time their smiles in a purposeful, goal-oriented manner.</text></s><s sid="6"><CoreSc1 advantage="None" conceptID="Met6" novelty="None" type="Met"/><text> In our study, mothers consistently attempted to maximize the time spent in mutual smiling, while infants tried to maximize mother-only smile time.</text></s><s sid="7"><CoreSc1 advantage="None" conceptID="Met7" novelty="None" type="Met"/><text> To validate this finding, we ported the smile timing strategy used by infants to a sophisticated child-like robot that automatically perceived and produced smiles while interacting with adults.</text></s><s sid="8"><CoreSc1 advantage="None" conceptID="Met8" novelty="None" type="Met"/><text> As predicted, this strategy proved successful at maximizing adult-only smile time.</text></s><s sid="9"><CoreSc1 advantage="None" conceptID="Met9" novelty="None" type="Met"/><text> The results indicate that by 4 months of age infants interact with their mothers in a goal-oriented manner, utilizing a sophisticated understanding of timing in social interactions.</text></s><s sid="10"><CoreSc1 advantage="None" conceptID="Met10" novelty="None" type="Met"/><text> Our work suggests that control theory is a promising technique for both analyzing complex interactive behavior and providing new insights into the development of social communication.</text></s></abstract>
    </front>
    <body class="DoCO:BodyMatter">
      <section class="DoCO:Section"><s sid="11"><CoreSc1 advantage="None" conceptID="Met11" novelty="None" type="Met"/><text>
        <h1 class="DoCO:SectionTitle" column="1" id="10" page="1">Introduction: Mother-Infant Interaction Study</h1>
        <outsider class="DoCO:TextBox" column="1" id="11" page="1" type="sidenote">Received: August 20, 2014 Accepted: August 4, 2015 Published: September 23, 2015 Copyright: © 2015 Ruvolo et al. This is an open access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.</outsider>
        <outsider class="DoCO:TextBox" column="1" id="12" page="1" type="sidenote">Data Availability Statement: All data are within the paper and its Supporting Information files.</outsider>
        <outsider class="DoCO:TextBox" column="1" id="13" page="1" type="sidenote">Funding: This research was supported by grants from the National Science Foundation (INT2 —-0808767 &amp; BCS1052736) and the National Institutes of Health (GM105004 MH 48680).</outsider>
        <outsider class="DoCO:TextBox" column="1" id="14" page="1" type="sidenote">Competing Interests: The authors have declared that no competing interests exist.</outsider>
      </text></s></section>
